### ISSUE TITLE
Sinch Noise Disturbance Issuse

### ISSUE THREAD

**Issue by vikasgrover33** [sinch/android-video-calling#2]
I am working sinch video application, there is high noise disturbance when calling, i am not able to listen the voice of opponent, even not able to speak anything, all i have to disconnect the call. There is any quick way to reduce the noise disturbance.

**Comment by slavasav** [comment]
Hi,
This is related to AudioManager mode, which should be set to MODE_IN_COMMUNICATION while in the call. We have implemented a fix in 3.9.2 release, please try it.

**Comment by vikasgrover33** [comment]
Hi,


I already done with this solution, but problem remains same on some of the
devices like micromax android one, micromax yophoria.

**Comment by slavasav** [comment]
Hi,
I see. Is the Android version 5.1 or later? We are also aware of a problem with loudspeaker echo cancellation on these versions, especially when speaker volume is over 50% (assuming you are testing with devices not in the same room). We plan to address this in the video GA release.

**Comment by vikasgrover33** [comment]
Yes you are right, there is any quick solution to this problem, and when
would this issue will be resolved,  its big.

**Comment by slavasav** [comment]
Unfortunately it is Android 5 specific, please see this issue https://code.google.com/p/android/issues/detail?id=159133
We are looking for a solution to this.

**Comment by vikasgrover33** [comment]
I don't think so its android 5.0 specific issue, because i am testing on
micromax yuphoria which is cyanogen.  So i think it might be issue of
cyanogen.

**Comment by slavasav** [comment]
Interesting. Can you please test some other communication app with speaker enabled on the same phone? Thanks.

**Comment by vikasgrover33** [comment]
Ya sure...  There are hugh number of bugs in the sdk, which are very
important,  which i can tell but not possible by email.

**Comment by XioZ** [comment]
has this issue been resolved yet? or is there any workaround? it'd be really grateful if someone can share...

**Comment by slavasav** [comment]
Hi,
We are not aware of any general problems with noise disturbance. Please specify your device, os version, sdk version, and a recording of how "nouse" spunds like would be great.
Thanks
